- name: Download "node_exporter" release archive to /tmp
  get_url:
    url: "{{ node_url }}"
    dest: "/tmp/node_exporter-1.6.1.linux-amd64.tar.gz"
    mode: 0644
- name: Calculate SHA-256 checksum
  command: sha256sum /tmp/node_exporter-1.6.1.linux-amd64.tar.gz
  register: sha256_output
- name: Display SHA-256 checksum
  debug:
    var: sha256_output.stdout_lines[0]
- name: Extract "node_exporter" release archive
  ansible.builtin.unarchive:
    src: "/tmp/node_exporter-1.6.1.linux-amd64.tar.gz"
    dest: "/tmp"
    remote_src: yes
- name: Clean up the archive
  file:
    path: "/tmp/node_exporter-1.6.1.linux-amd64.tar.gz"
    state: absent
- name: Copy "node_exporter" binary to /usr/local/bin
  copy:
    src: /tmp/node_exporter-1.6.1.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    owner: "{{ n_user }}"
    group: "{{ n_user }}"
    mode: 0755
    remote_src: true
- name: Delete /tmp/node_exporter-1.6.1.linux-amd64 directory
  file:
    path: /tmp/node_exporter-1.6.1.linux-amd64
    state: absent
- name: Render Node Exporter Configuration from Jinja2 Template
  template:
    src: /home/grahesh/.ansible/ansible-project2/NodeExporter/templates/node_exporter_config.j2 # Provide the path to your Jinja2 template
    dest: /tmp/node_exporter_config.yml # Temporary file to store the rendered configuration

- name: Replace the content of /etc/systemd/system/node_exporter.service
  template:
    src: /home/grahesh/.ansible/ansible-project2/NodeExporter/templates/node_exporter_service.j2 # Provide the path to your Jinja2 template
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: Reload node systemd
- name: Reload systemd to apply changes
  systemd:
    name: "{{ n_user }}"
    state: restarted
- name: Enable the node_exporter service
  systemd:
    name: "{{ n_user }}"
    enabled: yes
- name: Restart Prometheus
  systemd:
    name: prometheus
    state: restarted
  become: true
