p_user: "prometheus"
n_user: "node_exporter"
prometheus_url: "https://github.com/prometheus/prometheus/releases/download/v2.47.1/prometheus-2.47.1.linux-amd64.tar.gz"
ansible_ssh_user: ec2-user
ansible_ssh_private_key_file: /home/grahesh/.ansible/ansible-project2/prometheus/files/LoadTest.pem